services:
  olm-d-rch:
    build:
      target: development
    ports: !override
      - "${OLM_D_RCH_BIND_IP:-0.0.0.0}:${OLM_D_RCH_DEV_PORT:-8001}:8000"
    volumes:
      - ./src:/app/src
    environment:
      - CONTAINER_ENV=development
