version: "3.9"

services:
  research-api:
    volumes:
      - ./src:/app/src
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434/
    depends_on:
      ollama:
        condition: service_healthy

  ollama:
    build:
      context: ./ollama
      args:
        BUILT_IN_OLLAMA_MODELS: "qwen3:0.6b"
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:11434/api/tags" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  ollama-data:
    driver: local
    name: ${RESEARCH_API_PROJECT_NAME:-ollama-deep-researcher}-ollama-data
    external: false
