services:
  research-api:
    build:
      target: development
    ports: !override
      - "${RESEARCH_API_HOST_IP:-0.0.0.0}:${RESEARCH_API_DEV_PORT:-8001}:8000"
    volumes:
      - ./src:/app/src
    environment:
      - CONTAINER_ENV=development
      - SEARXNG_SECRET=${SEARXNG_SECRET}
      - OLLAMA_HOST=${OLLAMA_HOST-http://ollama:11434}
      - RESEARCH_API_OLLAMA_MODEL=${RESEARCH_API_OLLAMA_MODEL-tinyllama:1.1b}
    depends_on:
      ollama:
        condition: service_healthy

  ollama:
    image: ghcr.io/akitorahayashi/olm-ci-img:tinyllama-v1
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:11434/api/tags" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  ollama-data:
    driver: local
    name: ollama-data
    external: false
