version: "3.9"

services:
  research-api:
    build: .
    ports:
      - "${API_HOST_PORT:-8000}:8000"
    env_file:
      - .env
    depends_on:
      - ollama

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_MODELS=tinyllama:1.1b

volumes:
  ollama_data:
