version: "3.9"

services:
  research-api:
    build:
      target: development
    volumes:
      - ./src:/app/src
    environment:
      - OLLAMA_HOST=http://ollama:11434/
      - CONTAINER_ENV=development
    depends_on:
      ollama:
        condition: service_healthy

  ollama:
    image: ghcr.io/famiclone/ol-ci-img:tinyllama-v1
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:11434/api/tags" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  ollama-data:
    driver: local
    name: ${RESEARCH_API_PROJECT_NAME:-ollama-deep-researcher}-ollama-data
    external: false
