services:
  research-api:
    build:
      target: development
    ports: !override
      - "${RESEARCH_API_HOST_IP:-127.0.0.1}:${RESEARCH_API_TEST_PORT:-8002}:8000"
    environment:
      - CONTAINER_ENV=development
      - DEBUG=False
      - OLLAMA_HOST=${OLLAMA_HOST}
      - RESEARCH_API_OLLAMA_MODEL=${RESEARCH_API_OLLAMA_MODEL}
