services:
  olm-d-rch:
    build:
      target: production
    ports:
      - "${OLM_D_RCH_BIND_IP:-0.0.0.0}:${OLM_D_RCH_BIND_PORT:-8000}:8000"
    env_file:
      - .env
    environment:
      - CONTAINER_ENV=production
      - OLLAMA_HOST=${OLLAMA_HOST}
      - OLM_D_RCH_OLLAMA_MODEL=${OLM_D_RCH_OLLAMA_MODEL}
