version: "3.9"

services:
  research-api:
    build:
      target: production
    environment:
      - CONTAINER_ENV=production
    ports:
      - "${RESEARCH_API_HOST_IP:-0.0.0.0}:${RESEARCH_API_HOST_PORT:-8000}:8000"
    env_file:
      - .env
