services:
  research-api:
    build:
      target: development
    ports: !override
      - "${RESEARCH_API_HOST_IP:-127.0.0.1}:${RESEARCH_API_TEST_PORT:-8002}:8000"
    environment:
      - CONTAINER_ENV=development
      - DEBUG=False
      - OLLAMA_HOST=${OLLAMA_HOST-http://ollama:11434}
      - RESEARCH_API_OLLAMA_MODEL=tinyllama:1.1b
    depends_on:
      ollama:
        condition: service_healthy

  ollama:
    image: ghcr.io/akitorahayashi/olm-ci-img:tinyllama-v1
    volumes:
      - ollama-data:/root/.ollama
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:11434/api/tags" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  ollama-data:
    driver: local
    name: ollama-data
    external: false
