name: Run Tests

on:
  workflow_call:

permissions:
  contents: read

jobs:
  test:
    runs-on: self-hosted
    strategy:
      matrix:
        test_target: [unit-test, mock-test, intg-test, build-test]
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ensure toolcache dir
        run: mkdir -p "${{ runner.temp }}/_tool"

      - name: Set up Python
        uses: actions/setup-python@v5
        env:
          RUNNER_TOOL_CACHE: ${{ runner.temp }}/_tool
          AGENT_TOOLSDIRECTORY: ${{ runner.temp }}/_tool
          RUNNER_TEMP: ${{ runner.temp }}
        with:
          python-version: '3.12.7'

      - name: Install uv
        run: pipx install uv

      - name: Install dependencies
        run: uv sync --frozen

      - name: Install just
        uses: extractions/setup-just@v2

      - name: Create .env file
        run: cp .env.example .env

      - name: Run tests
        run: just ${{ matrix.test_target }}

      - name: Clean up workspace
        if: always()
        run: |
          rm -rf "$GITHUB_WORKSPACE"/*
          rm -rf "${{ runner.temp }}/_tool"
