name: Run Tests

on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      OLLAMA_HOST: ${{ secrets.OLLAMA_HOST }}
      DEBUG: "true"
      RESEARCH_API_PROJECT_NAME: "ollama-deep-researcher"
      RESEARCH_API_HOST_IP: "127.0.0.1"
      RESEARCH_API_HOST_PORT: "8000"
      RESEARCH_API_DEV_PORT: "8001"
      RESEARCH_API_TEST_PORT: "8002"
      RESEARCH_API_OLLAMA_MODEL: "tinyllama:1.1b"
      SEARXNG_SECRET: ${{ secrets.SEARXNG_SECRET || 'test_secret_key' }}
      SEARXNG_URL: "http://localhost:8080"
    strategy:
      matrix:
        test_target: [unit-test, intg-test, build-test, e2e-test]
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: '.python-version'

      - name: Install uv
        run: pipx install uv

      - name: Install dependencies
        run: uv sync --frozen

      - name: Install just
        uses: extractions/setup-just@v2

      - name: Run tests
        run: |
          if [ "${{ matrix.test_target }}" = "e2e-test" ]; then
            export DEBUG=false
          fi
          just ${{ matrix.test_target }}
