name: Run Linters

on:
  workflow_call:

permissions:
  contents: read

jobs:
  run-linters:
    runs-on: self-hosted
    env:
      UV_CACHE_DIR: ./.uv-cache
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: uv sync --only-group dev --frozen

      - name: Run Linters
        run: just lint

      - name: Clean up workspace
        if: always()
        run: rm -rf "$GITHUB_WORKSPACE"/*
