name: Run Linters

on:
  workflow_call:

permissions:
  contents: read

jobs:
  run-linters:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Ensure toolcache dir
        run: mkdir -p "${{ runner.temp }}/_tool"

      - name: Set up Python
        uses: actions/setup-python@v5
        env:
          RUNNER_TOOL_CACHE: ${{ runner.temp }}/_tool
          AGENT_TOOLSDIRECTORY: ${{ runner.temp }}/_tool
          RUNNER_TEMP: ${{ runner.temp }}
        with:
          python-version: '3.12.7'

      - name: Install uv
        run: pipx install uv

      - name: Install dependencies
        run: uv sync --only-group dev --frozen

      - name: Install just
        uses: extractions/setup-just@v2

      - name: Run Linters
        run: just lint

      - name: Clean up workspace
        if: always()
        run: |
          rm -rf "$GITHUB_WORKSPACE"/*
          rm -rf "${{ runner.temp }}/_tool"
