name: Run Linters

on:
  workflow_call:

permissions:
  contents: read

jobs:
  run-linters:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.7'

      - name: Install uv
        run: pipx install uv

      - name: Install dependencies
        run: uv sync --only-group dev --frozen

      - name: Install just
        uses: extractions/setup-just@v2

      - name: Run Linters
        run: just lint